<a href="https://colab.research.google.com/github/GaneshKetham/Sales-Supply-Chain-Analytics/blob/main/Sales_Supply_Chain_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [33]:
import os

os.listdir('/content')

['.config', 'drive', 'sample_data']

In [34]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Dataset/DataCoSupplyChainDataset.csv' , encoding='latin1')


df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [35]:
import os
os.listdir('/content/drive/MyDrive')

['Colab Notebooks', 'Dataset']

In [36]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [37]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [39]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [40]:
missing=df.isnull().sum().sort_values(ascending=False)

missing=missing[missing>0]

In [41]:
missing_pct = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

missing_pct[missing_pct > 0]

Product Description    100.000000
Order Zipcode           86.239676
Customer Lname           0.004432
Customer Zipcode         0.001662
dtype: float64

In [42]:
df.shape

(180519, 53)

In [43]:
df.drop(columns=['Product Description'], inplace=True)

In [44]:
df.drop(columns=['Order Zipcode'], inplace=True)

In [45]:
df['Customer Lname']=df['Customer Lname'].fillna('unknown')

In [46]:
df['Customer Zipcode']=df['Customer Zipcode'].fillna('unknown')

In [47]:
df.isnull().sum()

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Delivery Status                  0
Late_delivery_risk               0
Category Id                      0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Email                   0
Customer Fname                   0
Customer Id                      0
Customer Lname                   0
Customer Password                0
Customer Segment                 0
Customer State                   0
Customer Street                  0
Customer Zipcode                 0
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
Order Customer Id                0
order date (DateOrders)          0
Order Id                         0
Order Item Cardprod Id           0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Id                    0
Order Item Product Price         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Item Total                 0
Order Profit Per Order           0
Order Region                     0
Order State                      0
Order Status                     0
Product Card Id                  0
Product Category Id              0
Product Image                    0
Product Name                     0
Product Price                    0
Product Status                   0
shipping date (DateOrders)       0
Shipping Mode                    0
dtype: int64

In [48]:
df.shape

(180519, 51)

In [49]:
df.isnull().sum()[df.isnull().sum() > 0]

Series([], dtype: int64)

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [Type, Days for shipping (real), Days for shipment (scheduled), Benefit per order, Sales per customer, Delivery Status, Late_delivery_risk, Category Id, Category Name, Customer City, Customer Country, Customer Email, Customer Fname, Customer Id, Customer Lname, Customer Password, Customer Segment, Customer State, Customer Street, Customer Zipcode, Department Id, Department Name, Latitude, Longitude, Market, Order City, Order Country, Order Customer Id, order date (DateOrders), Order Id, Order Item Cardprod Id, Order Item Discount, Order Item Discount Rate, Order Item Id, Order Item Product Price, Order Item Profit Ratio, Order Item Quantity, Sales, Order Item Total, Order Profit Per Order, Order Region, Order State, Order Status, Product Card Id, Product Category Id, Product Image, Product Name, Product Price, Product Status, shipping date (DateOrders), Shipping Mode]
Index: []

[0 rows x 51 columns]

In [52]:
df.duplicated().sum()

np.int64(0)

In [53]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                  object
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Product Card Id                    int64
Product Category Id                int64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 51 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180519 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180519 non-null  object
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Product Card Id                180519 non-null  int64
 44  Product Category Id            180519 non-null  int64
 45  Product Image                  180519 non-null  object
 46  Product Name                   180519 non-null  object
 47  Product Price                  180519 non-null  float64
 48  Product Status                 180519 non-null  int64
 49  shipping date (DateOrders)     180519 non-null  object
 50  Shipping Mode                  180519 non-null  object
dtypes: float64(12), int64(14), object(25)
memory usage: 70.2+ MB

In [55]:
df['order date (DateOrders)'] = pd.to_datetime(
    df['order date (DateOrders)']
)

df['shipping date (DateOrders)'] = pd.to_datetime(
    df['shipping date (DateOrders)']
)

In [56]:
df.dtypes

Type                                     object
Days for shipping (real)                  int64
Days for shipment (scheduled)             int64
Benefit per order                       float64
Sales per customer                      float64
Delivery Status                          object
Late_delivery_risk                        int64
Category Id                               int64
Category Name                            object
Customer City                            object
Customer Country                         object
Customer Email                           object
Customer Fname                           object
Customer Id                               int64
Customer Lname                           object
Customer Password                        object
Customer Segment                         object
Customer State                           object
Customer Street                          object
Customer Zipcode                         object
Department Id                             int64
Department Name                          object
Latitude                                float64
Longitude                               float64
Market                                   object
Order City                               object
Order Country                            object
Order Customer Id                         int64
order date (DateOrders)          datetime64[ns]
Order Id                                  int64
Order Item Cardprod Id                    int64
Order Item Discount                     float64
Order Item Discount Rate                float64
Order Item Id                             int64
Order Item Product Price                float64
Order Item Profit Ratio                 float64
Order Item Quantity                       int64
Sales                                   float64
Order Item Total                        float64
Order Profit Per Order                  float64
Order Region                             object
Order State                              object
Order Status                             object
Product Card Id                           int64
Product Category Id                       int64
Product Image                            object
Product Name                             object
Product Price                           float64
Product Status                            int64
shipping date (DateOrders)       datetime64[ns]
Shipping Mode                            object
dtype: object

In [57]:
df['order date (DateOrders)'].dt.year

0         2018
1         2018
2         2018
3         2018
4         2018
          ...
180514    2016
180515    2016
180516    2016
180517    2016
180518    2016
Name: order date (DateOrders), Length: 180519, dtype: int32

In [58]:
df['order date (DateOrders)'].dt.month

0         1
1         1
2         1
3         1
4         1
         ..
180514    1
180515    1
180516    1
180517    1
180518    1
Name: order date (DateOrders), Length: 180519, dtype: int32

In [59]:
(
    df['shipping date (DateOrders)'] -
    df['order date (DateOrders)']
).dt.days

0         3
1         5
2         4
3         3
4         2
         ..
180514    4
180515    3
180516    5
180517    3
180518    4
Length: 180519, dtype: int64

In [60]:
df[['order date (DateOrders)', 'shipping date (DateOrders)']].dtypes

order date (DateOrders)       datetime64[ns]
shipping date (DateOrders)    datetime64[ns]
dtype: object

In [61]:
df.drop(columns=['Customer Password'], inplace=True)

In [62]:
df.shape

(180519, 50)

In [63]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Days for shipping (real),180519.0,3.497654,0.0,2.0,3.0,5.0,6.0,1.623722
Days for shipment (scheduled),180519.0,2.931847,0.0,2.0,4.0,4.0,4.0,1.374449
Benefit per order,180519.0,21.974989,-4274.97998,7.0,31.52,64.800003,911.799988,104.433526
Sales per customer,180519.0,183.107609,7.49,104.379997,163.990005,247.399994,1939.98999,120.04367
Late_delivery_risk,180519.0,0.548291,0.0,0.0,1.0,1.0,1.0,0.497664
Category Id,180519.0,31.851451,2.0,18.0,29.0,45.0,76.0,15.640064
Customer Id,180519.0,6691.379495,1.0,3258.5,6457.0,9779.0,20757.0,4162.918106
Department Id,180519.0,5.44346,2.0,4.0,5.0,7.0,12.0,1.629246
Latitude,180519.0,29.719955,-33.937553,18.265432,33.144863,39.279617,48.781933,9.813646
Longitude,180519.0,-84.915675,-158.025986,-98.446312,-76.847908,-66.370583,115.263077,21.433241
Order Customer Id,180519.0,6691.379495,1.0,3258.5,6457.0,9779.0,20757.0,4162.918106
order date (DateOrders),180519,2016-06-12 17:47:04.669868544,2015-01-01 00:00:00,2015-09-21 13:49:00,2016-06-11 13:06:00,2017-03-01 08:42:00,2018-01-31 23:38:00,NaN
Order Id,180519.0,36221.894903,1.0,18057.0,36140.0,54144.0,77204.0,21045.379569
Order Item Cardprod Id,180519.0,692.509764,19.0,403.0,627.0,1004.0,1363.0,336.446807
Order Item Discount,180519.0,20.664741,0.0,5.4,14.0,29.99,500.0,21.800901
Order Item Discount Rate,180519.0,0.101668,0.0,0.04,0.1,0.16,0.25,0.070415
Order Item Id,180519.0,90260.0,1.0,45130.5,90260.0,135389.5,180519.0,52111.490959
Order Item Product Price,180519.0,141.23255,9.99,50.0,59.990002,199.990005,1999.98999,139.732492
Order Item Profit Ratio,180519.0,0.120647,-2.75,0.08,0.27,0.36,0.5,0.466796
Order Item Quantity,180519.0,2.127638,1.0,1.0,1.0,3.0,5.0,1.453451
Sales,180519.0,203.772096,9.99,119.980003,199.919998,299.950012,1999.98999,132.273077
Order Item Total,180519.0,183.107609,7.49,104.379997,163.990005,247.399994,1939.98999,120.04367
Order Profit Per Order,180519.0,21.974989,-4274.97998,7.0,31.52,64.800003,911.799988,104.433526
Product Card Id,180519.0,692.509764,19.0,403.0,627.0,1004.0,1363.0,336.446807
Product Category Id,180519.0,31.851451,2.0,18.0,29.0,45.0,76.0,15.640064
Product Price,180519.0,141.23255,9.99,50.0,59.990002,199.990005,1999.98999,139.732492
Product Status,180519.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
shipping date (DateOrders),180519,2016-06-16 05:45:23.202433024,2015-01-03 00:00:00,2015-09-25 06:59:00,2016-06-15 08:32:00,2017-03-04 21:29:00,2018-02-06 22:14:00,NaN

In [64]:
(df['Order Profit Per Order'] < 0).sum()

np.int64(33784)

In [65]:
df[df['Order Profit Per Order'] < 0][
    ['Order Id', 'Sales', 'Order Item Total',
     'Order Item Discount', 'Order Profit Per Order']
].head(10)

,Order Id,Sales,Order Item Total,Order Item Discount,Order Profit Per Order
1,75939,327.750000,311.359985,16.389999,-249.089996
2,75938,327.750000,309.720001,18.030001,-247.779999
15,75925,327.750000,324.470001,3.280000,-259.579987
16,75924,327.750000,321.200012,6.560000,-246.360001
28,75912,327.750000,272.029999,55.720001,-17.139999
33,75907,327.750000,324.470001,3.280000,-97.339996
34,75906,327.750000,321.200012,6.560000,-425.579987
48,28744,119.980003,115.180000,4.800000,-30.750000
49,45461,79.980003,79.180000,0.800000,-122.730003
53,50054,100.000000,87.000000,13.000000,-21.750000

In [66]:
df.nlargest(10, 'Order Profit Per Order')[
    ['Order Id', 'Sales', 'Order Item Discount',
     'Order Item Total', 'Order Profit Per Order']
]

,Order Id,Sales,Order Item Discount,Order Item Total,Order Profit Per Order
175116,68883,1999.98999,60.0,1939.98999,911.799988
48281,68821,1999.98999,200.0,1799.98999,864.000000
82161,68724,1999.98999,360.0,1639.98999,721.599976
43944,70558,1500.00000,30.0,1470.00000,720.299988
58471,70668,1500.00000,0.0,1500.00000,720.000000
120277,70686,1500.00000,0.0,1500.00000,720.000000
148372,70701,1500.00000,45.0,1455.00000,712.950012
40363,70536,1500.00000,82.5,1417.50000,708.750000
82013,70684,1500.00000,30.0,1470.00000,705.599976
97113,70702,1500.00000,30.0,1470.00000,705.599976

In [67]:
df.nsmallest(10, 'Order Profit Per Order')[
    ['Order Id', 'Sales', 'Order Item Discount',
     'Order Item Total', 'Order Profit Per Order']
]

,Order Id,Sales,Order Item Discount,Order Item Total,Order Profit Per Order
63990,68859,1999.98999,100.0,1899.98999,-4274.97998
169249,70533,1500.00000,150.0,1350.00000,-3442.50000
8259,74556,1500.00000,180.0,1320.00000,-3366.00000
126391,70760,1500.00000,300.0,1200.00000,-3000.00000
33845,74508,1500.00000,60.0,1440.00000,-2592.00000
12516,70560,1500.00000,0.0,1500.00000,-2550.00000
84975,70537,1500.00000,75.0,1425.00000,-2351.25000
11909,70845,1500.00000,45.0,1455.00000,-2328.00000
97532,70753,1500.00000,75.0,1425.00000,-2280.00000
82022,70683,1500.00000,45.0,1455.00000,-2255.25000

In [68]:
print("Sales <= 0:", (df['Sales'] <= 0).sum())
print("Quantity <= 0:", (df['Order Item Quantity'] <= 0).sum())
print("Product Price <= 0:", (df['Product Price'] <= 0).sum())
print("Discount < 0:", (df['Order Item Discount'] < 0).sum())

Sales <= 0: 0
Quantity <= 0: 0
Product Price <= 0: 0
Discount < 0: 0

In [69]:
print("Actual shipping days < 0:",
      (df['Days for shipping (real)'] < 0).sum())

print("Scheduled shipping days < 0:",
      (df['Days for shipment (scheduled)'] < 0).sum())

Actual shipping days < 0: 0
Scheduled shipping days < 0: 0

In [70]:
df['Year'] = df['order date (DateOrders)'].dt.year

In [71]:
df['Month'] = df['order date (DateOrders)'].dt.month

In [72]:
df['Quarter'] = df['order date (DateOrders)'].dt.quarter

In [73]:
df['Month-Year'] = df['order date (DateOrders)'].dt.to_period('M').astype(str)

In [74]:
df['Day of Week'] = df['order date (DateOrders)'].dt.day_name()

In [75]:
df['Delivery Gap'] = (
    df['Days for shipping (real)']
    - df['Days for shipment (scheduled)']
)

In [76]:
df[['Year', 'Month', 'Quarter', 'Month-Year',
    'Day of Week', 'Delivery Gap']].head()

   Year  Month  Quarter Month-Year Day of Week  Delivery Gap
0  2018      1        1    2018-01   Wednesday            -1
1  2018      1        1    2018-01    Saturday             1
2  2018      1        1    2018-01    Saturday             0
3  2018      1        1    2018-01    Saturday            -1
4  2018      1        1    2018-01    Saturday            -2

In [77]:
df[
    ['Year', 'Month', 'Quarter', 'Month-Year',
     'Day of Week', 'Delivery Gap']
].head(10)

   Year  Month  Quarter Month-Year Day of Week  Delivery Gap
0  2018      1        1    2018-01   Wednesday            -1
1  2018      1        1    2018-01    Saturday             1
2  2018      1        1    2018-01    Saturday             0
3  2018      1        1    2018-01    Saturday            -1
4  2018      1        1    2018-01    Saturday            -2
5  2018      1        1    2018-01    Saturday             2
6  2018      1        1    2018-01    Saturday             1
7  2018      1        1    2018-01    Saturday             1
8  2018      1        1    2018-01    Saturday             1
9  2018      1        1    2018-01    Saturday             1

In [78]:
df['Delivery Gap'].value_counts().sort_index()

Delivery Gap
-2    21666
-1    21700
 0    33753
 1    60647
 2    28718
 3     7052
 4     6983
Name: count, dtype: int64

In [79]:
df['Delivery Gap'].describe()

count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Delivery Gap, dtype: float64

In [81]:
print("Total Sales:", df['Sales'].sum())
print("Total Profit:", df['Order Profit Per Order'].sum())
print("Total Orders:", df['Order Id'].nunique())
print("Average Order Value:", df['Sales'].sum() / df['Order Id'].nunique())
print("Profit Margin (%):",
      (df['Order Profit Per Order'].sum() / df['Sales'].sum()) * 100)
print("Late Delivery Rate (%):",
      df['Late_delivery_risk'].mean() * 100)
print("Average Actual Shipping Days:",
      df['Days for shipping (real)'].mean())
print("Average Scheduled Shipping Days:",
      df['Days for shipment (scheduled)'].mean())

Total Sales: 36784735.01337984
Total Profit: 3966902.9740503575
Total Orders: 65752
Average Order Value: 559.4466330055335
Profit Margin (%): 10.784100993543822
Late Delivery Rate (%): 54.82913155955883
Average Actual Shipping Days: 3.4976539865609713
Average Scheduled Shipping Days: 2.931846509231715

In [82]:
year_analysis = df.groupby('Year').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).reset_index()

year_analysis

   Year         Sales        Profit  Orders
0  2015  1.234083e+07  1.318857e+06   20904
1  2016  1.230382e+07  1.310119e+06   20859
2  2017  1.180844e+07  1.304085e+06   21866
3  2018  3.316501e+05  3.384189e+04    2123

In [84]:
monthly_analysis = df.groupby('Month').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).reset_index()

monthly_analysis

    Month         Sales         Profit  Orders
0       1  3.459246e+06  367127.430615    7427
1       2  2.888088e+06  301061.220935    4849
2       3  3.125112e+06  333727.100652    5327
3       4  3.053996e+06  339021.360056    5155
4       5  3.185364e+06  337878.660269    5302
5       6  3.059152e+06  324742.520726    5091
6       7  3.188170e+06  348592.480100    5297
7       8  3.187032e+06  360210.470630    5296
8       9  3.164511e+06  359315.040248    5159
9      10  3.171279e+06  331987.009971    5652
10     11  2.703625e+06  281757.810287    5505
11     12  2.599160e+06  281481.869563    5692

In [85]:
category_analysis = df.groupby('Category Name').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).sort_values('Sales', ascending=False).reset_index()

category_analysis

           Category Name         Sales         Profit  Orders
0                Fishing  6.929654e+06  756220.767190   15164
1                 Cleats  4.431943e+06  494636.919791   20386
2       Camping & Hiking  4.118426e+06  427455.568106   12299
3       Cardio Equipment  3.694843e+06  383011.098485   11355
4        Women's Apparel  3.147800e+06  350421.029567   17869
5           Water Sports  3.113845e+06  325146.960038   13758
6         Men's Footwear  2.891758e+06  311902.820214   18783
7   Indoor/Outdoor Games  2.888994e+06  318451.430554   16623
8          Shop By Sport  1.309522e+06  129813.960315   10136
9              Computers  6.630000e+05   69656.810171     442
10           Electronics  3.710346e+05   40891.379918    3061
11              Cameras   2.676077e+05   30289.799946     592
12                Garden  2.577687e+05   33443.010106     484
13   Children's Clothing  2.328292e+05   27178.099597     652
14                Crafts  2.233563e+05   25531.170060     484
15        Girls' Apparel  1.517062e+05   17288.569973    1191
16      Women's Clothing  1.402830e+05   19102.849930     650
17           Accessories  1.336715e+05   16643.520074    1753
18        Sporting Goods  1.170068e+05   12518.610119     357
19           Golf Gloves  1.166954e+05   12975.490078    1064
20                 Music  1.131221e+05   14436.319923     434
21  Consumer Electronics  1.089913e+05   13223.399926     431
22            Golf Shoes  1.079980e+05   12406.070143     523
23     Health and Beauty  1.060805e+05    9493.629974     362
24      Kids' Golf Clubs  9.879758e+04    9045.839896     373
25   Baseball & Softball  9.405715e+04   12762.130067     628
26          Boxing & MMA  8.520541e+04    8641.370006     421
27                  DVDs  7.939554e+04    6655.430088     483
28            Golf Balls  7.709816e+04    8342.670024    1444
29              Trade-In  6.872178e+04    7915.369985     964
30    Hunting & Shooting  5.684842e+04    5979.999945     436
31     Strength Training  5.489553e+04     332.310091     111
32                Hockey  4.836073e+04    5397.430013     609
33      Men's Golf Clubs  4.703580e+04    5517.989977     280
34      Tennis & Racquet  4.458509e+04    5747.979996     327
35    Women's Golf Clubs  4.454597e+04    5028.639929     181
36        Men's Clothing  4.385680e+04    2006.039969     208
37          Pet Supplies  4.152480e+04    3589.259959     492
38              Lacrosse  3.946479e+04    4364.289984     341
39   Fitness Accessories  3.560144e+04    5258.390016     307
40          Golf Apparel  3.496975e+04    3496.309983     440
41           Video Games  3.331050e+04    2717.519997     838
42            Basketball  2.709933e+04    1845.670003      64
43                Soccer  2.647705e+04    3901.949953     136
44       As Seen on  TV!  2.059794e+04     714.429980      68
45                Books   1.258740e+04     883.010008     405
46                 Baby   1.222956e+04    1525.029992     207
47     Golf Bags & Carts  1.036939e+04    1810.069992      61
48                  Toys  6.104660e+03     900.710000     529
49                  CDs   3.059590e+03     383.850000     271

In [86]:
department_analysis = df.groupby('Department Name').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).sort_values('Sales', ascending=False).reset_index()

department_analysis

       Department Name         Sales        Profit  Orders
0             Fan Shop  1.711387e+07  1.834155e+06   41303
1              Apparel  7.976255e+06  8.818829e+05   35190
2                 Golf  4.609028e+06  4.975236e+05   25889
3             Footwear  4.006499e+06  4.102225e+05   13009
4             Outdoors  1.253351e+06  1.452515e+05    9066
5           Technology  1.039599e+06  1.131700e+05    1465
6              Fitness  3.970509e+05  4.653806e+04    2437
7           Discs Shop  2.288877e+05  2.419312e+04    2026
8   Health and Beauty   1.060805e+05  9.493630e+03     362
9             Pet Shop  4.152480e+04  3.589260e+03     492
10           Book Shop  1.258740e+04  8.830100e+02     405

In [87]:
segment_analysis = df.groupby('Customer Segment').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).sort_values('Sales', ascending=False).reset_index()

segment_analysis

  Customer Segment         Sales        Profit  Orders
0         Consumer  1.909579e+07  2.073488e+06   34119
1        Corporate  1.116841e+07  1.202575e+06   19856
2      Home Office  6.520538e+06  6.908403e+05   11777

In [88]:
market_analysis = df.groupby('Market').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).sort_values('Sales', ascending=False).reset_index()

market_analysis

         Market         Sales        Profit  Orders
0        Europe  1.087240e+07  1.169443e+06   18561
1         LATAM  1.027761e+07  1.123322e+06   17181
2  Pacific Asia  8.273744e+06  8.577534e+05   17577
3          USCA  5.066529e+06  5.643138e+05    8579
4        Africa  2.294453e+06  2.520712e+05    3854

In [89]:
region_analysis = df.groupby('Order Region').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).sort_values('Sales', ascending=False).reset_index()

region_analysis

       Order Region         Sales         Profit  Orders
0    Western Europe  5.894381e+06  625446.080548   10010
1   Central America  5.665712e+06  616341.570651    9396
2     South America  2.960881e+06  335154.400817    4979
3   Northern Europe  2.155831e+06  233450.600647    3716
4   Southern Europe  2.047919e+06  230829.229883    3543
5           Oceania  2.016654e+06  201478.020484    4362
6    Southeast Asia  1.932496e+06  211342.819786    4356
7         Caribbean  1.651019e+06  171825.640024    2806
8      West of USA   1.571416e+06  164940.660455    2667
9        South Asia  1.553681e+06  165703.900124    3335
10     Eastern Asia  1.486401e+06  147368.010614    3318
11      East of USA  1.371112e+06  156263.300194    2323
12        West Asia  1.174672e+06  118815.410047    2022
13       US Center   1.151356e+06  131094.229875    1935
14   South of  USA   7.857839e+05   88114.879898    1345
15   Eastern Europe  7.742666e+05   79717.049920    1292
16      West Africa  7.279512e+05   80030.270031    1223
17     North Africa  6.347522e+05   64599.860009    1064
18      East Africa  3.762349e+05   43167.729927     613
19   Central Africa  3.272630e+05   33447.269960     556
20  Southern Africa  2.282516e+05   30826.050146     398
21           Canada  1.868610e+05   23900.709960     309
22     Central Asia  1.098399e+05   13045.280051     184

In [90]:
delivery_analysis = df.groupby('Delivery Status').agg(
    Orders=('Order Id', 'nunique'),
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum')
).reset_index()

delivery_analysis

     Delivery Status  Orders         Sales        Profit
0   Advance shipping   15127  8.518008e+06  9.352253e+05
1      Late delivery   36048  2.012640e+07  2.140052e+06
2  Shipping canceled    2855  1.570305e+06  1.604823e+05
3   Shipping on time   11722  6.570026e+06  7.311437e+05

In [91]:
shipping_analysis = df.groupby('Shipping Mode').agg(
    Orders=('Order Id', 'nunique'),
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Avg_Shipping_Days=('Days for shipping (real)', 'mean'),
    Late_Rate=('Late_delivery_risk', 'mean')
).reset_index()

shipping_analysis['Late_Rate'] = shipping_analysis['Late_Rate'] * 100

shipping_analysis

,Shipping Mode,Orders,Sales,Profit,Avg_Shipping_Days,Late_Rate
0,First Class,10079,5.674370e+06,6.431219e+05,2.000000,95.322499
1,Same Day,3571,1.942529e+06,2.030184e+05,0.478279,45.743042
2,Second Class,12778,7.145445e+06,7.503082e+05,3.990828,76.632781
3,Standard Class,39324,2.202239e+07,2.370454e+06,3.995907,38.071683

In [92]:
delivery_gap_shipping = df.groupby('Shipping Mode').agg(
    Avg_Delivery_Gap=('Delivery Gap', 'mean'),
    Orders=('Order Id', 'nunique'),
    Late_Rate=('Late_delivery_risk', 'mean')
).reset_index()

delivery_gap_shipping['Late_Rate'] = delivery_gap_shipping['Late_Rate'] * 100

delivery_gap_shipping

    Shipping Mode  Avg_Delivery_Gap  Orders  Late_Rate
0     First Class          1.000000   10079  95.322499
1        Same Day          0.478279    3571  45.743042
2    Second Class          1.990828   12778  76.632781
3  Standard Class         -0.004093   39324  38.071683

In [93]:
region_delivery = df.groupby('Order Region').agg(
    Orders=('Order Id', 'nunique'),
    Avg_Delivery_Gap=('Delivery Gap', 'mean'),
    Late_Rate=('Late_delivery_risk', 'mean'),
    Avg_Shipping_Days=('Days for shipping (real)', 'mean')
).reset_index()

region_delivery['Late_Rate'] = region_delivery['Late_Rate'] * 100

region_delivery = region_delivery.sort_values(
    'Late_Rate', ascending=False
)

region_delivery

       Order Region  Orders  Avg_Delivery_Gap  Late_Rate  Avg_Shipping_Days
2    Central Africa     556          0.639833  57.960644           3.560525
13       South Asia    3335          0.597465  56.266977           3.502005
5       East Africa     613          0.570734  55.939525           3.514579
22   Western Europe   10010          0.597403  55.848611           3.498432
14   South of  USA     1345          0.579975  55.772559           3.492707
8    Eastern Europe    1292          0.579847  55.663265           3.500765
6       East of USA    2323          0.584816  55.661605           3.500940
15   Southeast Asia    4356          0.558235  55.529930           3.496698
4      Central Asia     184          0.645570  55.334539           3.417722
20        West Asia    2022          0.569479  55.283741           3.486770
18       US Center     1935          0.587226  55.240360           3.457618
3   Central America    9396          0.561942  54.754596           3.510462
9      North Africa    1064          0.552290  54.517327           3.480507
17  Southern Europe    3543          0.515640  54.384477           3.435797
7      Eastern Asia    3318          0.566484  54.326923           3.527335
12    South America    4979          0.556344  54.308671           3.505725
10  Northern Europe    3716          0.546875  54.044118           3.502349
11          Oceania    4362          0.556267  54.020497           3.496354
21     West of USA     2667          0.557238  53.959715           3.504942
16  Southern Africa     398          0.478825  53.327571           3.446845
1         Caribbean    2806          0.546526  53.077663           3.507213
19      West Africa    1223          0.550595  52.840909           3.534091
0            Canada     309          0.391032  48.800834           3.331595

In [94]:
profit_category = df.groupby('Category Name').agg(
    Sales=('Sales', 'sum'),
    Profit=('Order Profit Per Order', 'sum'),
    Orders=('Order Id', 'nunique')
).reset_index()

profit_category['Profit_Margin'] = (
    profit_category['Profit'] / profit_category['Sales']
) * 100

profit_category = profit_category.sort_values(
    'Profit_Margin', ascending=False
)

profit_category

           Category Name         Sales         Profit  Orders  Profit_Margin
23     Golf Bags & Carts  1.036939e+04    1810.069992      61      17.455896
19   Fitness Accessories  3.560144e+04    5258.390016     307      14.770161
43                  Toys  6.104660e+03     900.710000     529      14.754466
39                Soccer  2.647705e+04    3901.949953     136      14.737102
48      Women's Clothing  1.402830e+05   19102.849930     650      13.617366
3    Baseball & Softball  9.405715e+04   12762.130067     628      13.568484
20                Garden  2.577687e+05   33443.010106     484      12.974037
42      Tennis & Racquet  4.458509e+04    5747.979996     327      12.892157
36                 Music  1.131221e+05   14436.319923     434      12.761715
7                   CDs   3.059590e+03     383.850000     271      12.545799
2                  Baby   1.222956e+04    1525.029992     207      12.470031
0            Accessories  1.336715e+05   16643.520074    1753      12.451060
14  Consumer Electronics  1.089913e+05   13223.399926     431      12.132530
35      Men's Golf Clubs  4.703580e+04    5517.989977     280      11.731468
11   Children's Clothing  2.328292e+05   27178.099597     652      11.672977
44              Trade-In  6.872178e+04    7915.369985     964      11.517993
26            Golf Shoes  1.079980e+05   12406.070143     523      11.487315
15                Crafts  2.233563e+05   25531.170060     484      11.430690
21        Girls' Apparel  1.517062e+05   17288.569973    1191      11.396087
8               Cameras   2.676077e+05   30289.799946     592      11.318733
49    Women's Golf Clubs  4.454597e+04    5028.639929     181      11.288653
28                Hockey  4.836073e+04    5397.430013     609      11.160770
12                Cleats  4.431943e+06  494636.919791   20386      11.160724
47       Women's Apparel  3.147800e+06  350421.029567   17869      11.132252
25           Golf Gloves  1.166954e+05   12975.490078    1064      11.119111
32              Lacrosse  3.946479e+04    4364.289984     341      11.058693
30  Indoor/Outdoor Games  2.888994e+06  318451.430554   16623      11.022918
17           Electronics  3.710346e+05   40891.379918    3061      11.020906
18               Fishing  6.929654e+06  756220.767190   15164      10.912822
24            Golf Balls  7.709816e+04    8342.670024    1444      10.820842
34        Men's Footwear  2.891758e+06  311902.820214   18783      10.785925
40        Sporting Goods  1.170068e+05   12518.610119     357      10.699050
29    Hunting & Shooting  5.684842e+04    5979.999945     436      10.519202
13             Computers  6.630000e+05   69656.810171     442      10.506306
46          Water Sports  3.113845e+06  325146.960038   13758      10.441977
9       Camping & Hiking  4.118426e+06  427455.568106   12299      10.379101
10      Cardio Equipment  3.694843e+06  383011.098485   11355      10.366099
6           Boxing & MMA  8.520541e+04    8641.370006     421      10.141809
22          Golf Apparel  3.496975e+04    3496.309983     440       9.998098
38         Shop By Sport  1.309522e+06  129813.960315   10136       9.913079
31      Kids' Golf Clubs  9.879758e+04    9045.839896     373       9.155933
27     Health and Beauty  1.060805e+05    9493.629974     362       8.949460
37          Pet Supplies  4.152480e+04    3589.259959     492       8.643654
16                  DVDs  7.939554e+04    6655.430088     483       8.382624
45           Video Games  3.331050e+04    2717.519997     838       8.158148
5                 Books   1.258740e+04     883.010008     405       7.015031
4             Basketball  2.709933e+04    1845.670003      64       6.810759
33        Men's Clothing  4.385680e+04    2006.039969     208       4.574068
1        As Seen on  TV!  2.059794e+04     714.429980      68       3.468454
41     Strength Training  5.489553e+04     332.310091     111       0.605350

In [97]:
df.to_csv("DataCo_cleaned.csv", index=False)